// 把配音产物编译成渲染器可以直接 import 的静态数据。
//
// 为什么需要这一步：Remotion 的组件必须是纯函数，不能运行时读文件，而这一系列的
// 时间基准是音频（每段的旁白时长），不是字数。所以构建期把
//   .topic-work/timeline.json（每段秒数）
//   .topic-work/seg-NN.srt （每段的分句时间）
// 编译成 src/topics/<id>.voice.ts，组件只读这个模块。
//
// 分句时间来自 edge-tts 顺手写出的 SRT，不是另跑一遍对齐——Node 在本沙箱里不能
// spawn 子进程，ffprobe 那条路走不通。
//
//   node --experimental-strip-types scripts/topic-build.ts tu-que
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repo = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const topicId = process.argv[2] ?? "tu-que";
// 与 topic-voice.ts 同一套约定：英文系列用 `--dir=topics-en`。
const dirArg = process.argv.find((a) => a.startsWith("--dir="));
const dir = dirArg ? dirArg.slice("--dir=".length) : "topics";
const workDir = path.join(repo, dir === "topics" ? ".topic-work" : ".topic-work-en");

/** 每段尾部留出的呼吸帧数：旁白之间没有停顿，换屏会读成卡顿。 */
const TAIL_FRAMES = 24;

type Cue = { text: string; start: number; end: number };
type Timeline = { segments: { index: number; role: string; chars: number; seconds: number }[] };

const toSeconds = (t: string): number => {
  const m = t.match(/(\d\d):(\d\d):(\d\d),(\d\d\d)/);
  if (!m) return 0;
  return Number(m[1]) * 3600 + Number(m[2]) * 60 + Number(m[3]) + Number(m[4]) / 1000;
};

const parseSrt = (srt: string): Cue[] =>
  srt
    .replace(/\r/g, "")
    .trim()
    .split(/\n\s*\n/)
    .map((block) => {
      const lines = block.split("\n").filter((l) => l.trim() !== "");
      if (lines.length < 3) return null;
      const range = lines[1].match(/([\d:,]+)\s*-->\s*([\d:,]+)/);
      if (!range) return null;
      return {
        text: lines.slice(2).join(""),
        start: toSeconds(range[1]),
        end: toSeconds(range[2]),
      };
    })
    .filter((c): c is Cue => c !== null);

const timeline = JSON.parse(fs.readFileSync(path.join(workDir, "timeline.json"), "utf8")) as Timeline;
const pad = (n: number) => String(n).padStart(2, "0");

const segments = timeline.segments.map((seg) => {
  const srtPath = path.join(workDir, `seg-${pad(seg.index)}.srt`);
  const cues = fs.existsSync(srtPath) ? parseSrt(fs.readFileSync(srtPath, "utf8")) : [];
  const frames = Math.round(seg.seconds * 30) + TAIL_FRAMES;
  return {
    index: seg.index,
    role: seg.role,
    seconds: seg.seconds,
    frames,
    /** 该段在整片中的起始帧，由累计得出。 */
    startFrame: 0,
    cues,
  };
});

let acc = 0;
for (const seg of segments) {
  seg.startFrame = acc;
  acc += seg.frames;
}

const header = `// AUTO-GENERATED by scripts/topic-build.ts — 不要手改。
// 数据来源：.topic-work/timeline.json 与 .topic-work/seg-NN.srt（edge-tts 合成产物）。
// 改旁白之后必须重新合成并重跑本脚本，否则画面与声音会脱节。
`;

const body = `export type VoiceCue = { text: string; start: number; end: number };
export type VoiceSegment = {
  index: number;
  role: string;
  /** 该段旁白的实际秒数。 */
  seconds: number;
  /** 该段占用的帧数，含尾部呼吸。 */
  frames: number;
  /** 该段在整片中的起始帧。 */
  startFrame: number;
  /** 分句时间，相对该段起点，用于字幕高亮。 */
  cues: VoiceCue[];
};

export const voice: {
  topic: string;
  fps: number;
  totalFrames: number;
  segments: VoiceSegment[];
} = ${JSON.stringify({ topic: topicId, fps: 30, totalFrames: acc, segments }, null, 2)};
`;

fs.writeFileSync(path.join(repo, "src", dir, `${topicId}.voice.ts`), header + body, "utf8");
console.log(
  `wrote src/${dir}/${topicId}.voice.ts — ${segments.length} segments, ` +
    `${acc} frames = ${(acc / 30 / 60).toFixed(2)} min`,
);
