// AUTO-GENERATED by scripts/topic-build.ts — 不要手改。
// 数据来源：.topic-work/timeline.json 与 .topic-work/seg-NN.srt（edge-tts 合成产物）。
// 改旁白之后必须重新合成并重跑本脚本，否则画面与声音会脱节。
export type VoiceCue = { text: string; start: number; end: number };
export type VoiceSegment = {
  index: number;
  role: string;
  /** 该段旁白的实际秒数。 */
  seconds: number;
  /** 该段占用的帧数，含尾部呼吸。 */
  frames: number;
  /** 该段在整片中的起始帧。 */
  startFrame: number;
  /** 分句时间，相对该段起点，用于字幕高亮。 */
  cues: VoiceCue[];
};

export const voice: {
  topic: string;
  fps: number;
  totalFrames: number;
  segments: VoiceSegment[];
} = {
  "topic": "tu-que-en",
  "fps": 30,
  "totalFrames": 8852,
  "segments": [
    {
      "index": 1,
      "role": "title",
      "seconds": 27.32,
      "frames": 844,
      "startFrame": 0,
      "cues": [
        {
          "text": "In 1330, a court physician named Hu Sihui presented a book to the emperor of Mongol-ruled China.",
          "start": 0.1,
          "end": 6.95
        },
        {
          "text": "It listed foods, drinks, and their properties.",
          "start": 6.9,
          "end": 10.662
        },
        {
          "text": "Among them was one line: eating rabbit meat will cause a child to be born with a silent, split lip.",
          "start": 10.662,
          "end": 17.35
        },
        {
          "text": "Hu Sihui did not invent this.",
          "start": 17.35,
          "end": 20.125
        },
        {
          "text": "The warning was already fifteen hundred years old when he wrote it down, and at least fifty medical books would copy it after him.",
          "start": 20.125,
          "end": 27.325
        }
      ]
    },
    {
      "index": 2,
      "role": "quote",
      "seconds": 23.77,
      "frames": 737,
      "startFrame": 844,
      "cues": [
        {
          "text": "In Chinese, a cleft lip has a name: tu que, rabbit defect.",
          "start": 0.1,
          "end": 5.487
        },
        {
          "text": "A seventh-century medical text explains where the name comes from.",
          "start": 5.437,
          "end": 9.725
        },
        {
          "text": "A person born with a split lip, it says, looks like a rabbit's mouth.",
          "start": 9.725,
          "end": 14.762
        },
        {
          "text": "So that is what they called it.",
          "start": 14.762,
          "end": 17.112
        },
        {
          "text": "Listen to the logic.",
          "start": 17.112,
          "end": 19.25
        },
        {
          "text": "It looks like a rabbit.",
          "start": 19.25,
          "end": 21.275
        },
        {
          "text": "Not it was caused by a rabbit.",
          "start": 21.275,
          "end": 23.775
        }
      ]
    },
    {
      "index": 3,
      "role": "plain",
      "seconds": 15.54,
      "frames": 490,
      "startFrame": 1581,
      "cues": [
        {
          "text": "And in that same passage, the physician Chao Yuanfang did something careful.",
          "start": 0.1,
          "end": 5.337
        },
        {
          "text": "He marked where the warning came from.",
          "start": 5.287,
          "end": 7.95
        },
        {
          "text": "The world says, he wrote.",
          "start": 7.95,
          "end": 10.5
        },
        {
          "text": "He was recording it as a popular belief, not stating it as his own finding.",
          "start": 10.5,
          "end": 15.537
        }
      ]
    },
    {
      "index": 4,
      "role": "quote",
      "seconds": 22.86,
      "frames": 710,
      "startFrame": 2071,
      "cues": [
        {
          "text": "Trace it back further, and it leads to the Huainanzi, a philosophical compendium from the second century before the Common Era.",
          "start": 0.1,
          "end": 7.687
        },
        {
          "text": "A pregnant woman who sees a rabbit will bear a child with a split lip.",
          "start": 7.6370000000000005,
          "end": 12.075
        },
        {
          "text": "One who sees a moose will bear a child with four eyes.",
          "start": 12.075,
          "end": 16.025
        },
        {
          "text": "Nobody believes the second half anymore.",
          "start": 16.025,
          "end": 19.15
        },
        {
          "text": "The first half survived for fifteen hundred years.",
          "start": 19.15,
          "end": 22.862
        }
      ]
    },
    {
      "index": 5,
      "role": "plain",
      "seconds": 17.68,
      "frames": 554,
      "startFrame": 2781,
      "cues": [
        {
          "text": "It also grew stricter as it travelled.",
          "start": 0.1,
          "end": 3.075
        },
        {
          "text": "The Huainanzi said sees.",
          "start": 3.025,
          "end": 5.562
        },
        {
          "text": "By the time it reached the medical texts, it said eats.",
          "start": 5.562,
          "end": 9.562
        },
        {
          "text": "Seeing was bad.",
          "start": 9.562,
          "end": 11.5
        },
        {
          "text": "Eating was worse.",
          "start": 11.5,
          "end": 13.462
        },
        {
          "text": "A taboo getting heavier in the copying is a very common thing.",
          "start": 13.462,
          "end": 17.675
        }
      ]
    },
    {
      "index": 6,
      "role": "plain",
      "seconds": 16.34,
      "frames": 514,
      "startFrame": 3335,
      "cues": [
        {
          "text": "And it goes back even further.",
          "start": 0.1,
          "end": 2.625
        },
        {
          "text": "The Book of Rites, compiled before the Common Era, has a line about eating rabbit: remove the rump.",
          "start": 2.575,
          "end": 9.325
        },
        {
          "text": "It does not say why.",
          "start": 9.325,
          "end": 11.425
        },
        {
          "text": "Later writers supplied the reason.",
          "start": 11.425,
          "end": 14.025
        },
        {
          "text": "Because it is bad for you.",
          "start": 14.025,
          "end": 16.337
        }
      ]
    },
    {
      "index": 7,
      "role": "plain",
      "seconds": 19.65,
      "frames": 614,
      "startFrame": 3849,
      "cues": [
        {
          "text": "Later writers also supplied a mechanism.",
          "start": 0.1,
          "end": 3.387
        },
        {
          "text": "In the eighth century, Chen Zangqi explained that rabbits have a hole in their hindquarters and give birth through the mouth.",
          "start": 3.337,
          "end": 10.275
        },
        {
          "text": "Li Shizhen, the most famous pharmacologist in Chinese history, copied that explanation into his Compendium of Materia Medica in 1578.",
          "start": 10.275,
          "end": 19.65
        }
      ]
    },
    {
      "index": 8,
      "role": "plain",
      "seconds": 23.61,
      "frames": 732,
      "startFrame": 4463,
      "cues": [
        {
          "text": "Chen was wrong.",
          "start": 0.1,
          "end": 1.962
        },
        {
          "text": "But he was not making things up.",
          "start": 1.912,
          "end": 4.45
        },
        {
          "text": "Rabbits really do have unusual reproductive biology.",
          "start": 4.45,
          "end": 8.575
        },
        {
          "text": "They ovulate only after mating.",
          "start": 8.575,
          "end": 11.275
        },
        {
          "text": "They have two separate uteruses, and can carry two litters at once.",
          "start": 11.275,
          "end": 16.05
        },
        {
          "text": "To someone watching without modern biology, they were genuinely strange animals, and strangeness invites explanation.",
          "start": 16.05,
          "end": 23.612
        }
      ]
    },
    {
      "index": 9,
      "role": "quote",
      "seconds": 25.35,
      "frames": 785,
      "startFrame": 5195,
      "cues": [
        {
          "text": "Nor was everyone convinced.",
          "start": 0.1,
          "end": 2.6870000000000003
        },
        {
          "text": "A sixteenth-century text quotes the Huainanzi line and then pushes back.",
          "start": 2.637,
          "end": 7.612
        },
        {
          "text": "Things have their natural reasons, the author writes, but sometimes they do not look that way.",
          "start": 7.612,
          "end": 13.487
        },
        {
          "text": "His example: a moose appears to have four eyes.",
          "start": 13.487,
          "end": 17.412
        },
        {
          "text": "The back two are just night-eyes.",
          "start": 17.412,
          "end": 20.212
        },
        {
          "text": "Looking like something, he is saying, is not the same as being caused by it.",
          "start": 20.212,
          "end": 25.35
        }
      ]
    },
    {
      "index": 10,
      "role": "stat",
      "seconds": 18.02,
      "frames": 565,
      "startFrame": 5980,
      "cues": [
        {
          "text": "So how far did the warning actually spread?",
          "start": 0.1,
          "end": 3.237
        },
        {
          "text": "Search the full corpus of seven hundred and one classical Chinese medical texts, and the phrase appears in fifty-one of them, across a thousand years.",
          "start": 3.187,
          "end": 12.275
        },
        {
          "text": "It is not one book's oddity.",
          "start": 12.275,
          "end": 14.725
        },
        {
          "text": "It is a consensus of an entire literature.",
          "start": 14.725,
          "end": 18.025
        }
      ]
    },
    {
      "index": 11,
      "role": "quote",
      "seconds": 25.35,
      "frames": 785,
      "startFrame": 6545,
      "cues": [
        {
          "text": "But here is the part that makes it strange.",
          "start": 0.1,
          "end": 3.137
        },
        {
          "text": "In the surgical manuals, the same tradition, the same centuries, a cleft lip is a real condition with a real operation.",
          "start": 3.087,
          "end": 11.05
        },
        {
          "text": "One text describes a powder for closing a split lip.",
          "start": 11.05,
          "end": 14.937
        },
        {
          "text": "Another says the same powder also stops bleeding from a cut throat.",
          "start": 14.937,
          "end": 19.487
        },
        {
          "text": "The surgeons were repairing cleft lips while the physicians were copying down a warning about rabbit meat.",
          "start": 19.487,
          "end": 25.35
        }
      ]
    },
    {
      "index": 12,
      "role": "plain",
      "seconds": 20.66,
      "frames": 644,
      "startFrame": 7330,
      "cues": [
        {
          "text": "Today we know how a cleft lip actually forms.",
          "start": 0.1,
          "end": 3.8120000000000003
        },
        {
          "text": "In the fourth to seventh week of pregnancy, the tissues that should join to form the upper lip fail to meet.",
          "start": 3.762,
          "end": 10.162
        },
        {
          "text": "Genetics and environment both play a part: smoking, alcohol, certain medications, folate deficiency.",
          "start": 10.162,
          "end": 17.812
        },
        {
          "text": "Rabbit meat plays no part at all.",
          "start": 17.812,
          "end": 20.662
        }
      ]
    },
    {
      "index": 13,
      "role": "closing",
      "seconds": 28.48,
      "frames": 878,
      "startFrame": 7974,
      "cues": [
        {
          "text": "But the ancients were not wrong about everything.",
          "start": 0.1,
          "end": 3.35
        },
        {
          "text": "What a mother eats and drinks during pregnancy really does matter.",
          "start": 3.3,
          "end": 7.362
        },
        {
          "text": "They had the concern right.",
          "start": 7.362,
          "end": 9.625
        },
        {
          "text": "They attached it to the wrong cause.",
          "start": 9.625,
          "end": 12.412
        },
        {
          "text": "And a warning that lasted fifteen hundred years may have started with nothing more than a name.",
          "start": 12.412,
          "end": 17.762
        },
        {
          "text": "Tu que.",
          "start": 17.762,
          "end": 19.35
        },
        {
          "text": "Rabbit defect.",
          "start": 19.35,
          "end": 21.287
        },
        {
          "text": "It looked like a rabbit, so they called it that.",
          "start": 21.287,
          "end": 24.525
        },
        {
          "text": "And somewhere along the way, the naming became the reason.",
          "start": 24.525,
          "end": 28.475
        }
      ]
    }
  ]
};
