// AUTO-GENERATED by scripts/ask-compositions.mjs — 不要手改。
// 加一集：在 asks/ 放 YAML，跑 ask:build 与 ask:voice，再跑本脚本。
// 系列总封面（AskSeriesCover）不是一集，但注册表只有这一份，所以它在这里固定注册。
import { Composition } from "remotion";
import { AskFilm } from "../ask-film";
import { AskSeriesCover } from "./series-cover-film";
import { content as dazaoYe } from "./dazao-ye.content";
import { voice as dazaoYeVoice } from "./dazao-ye.voice";
import { content as fangji } from "./fangji.content";
import { voice as fangjiVoice } from "./fangji.voice";
import { content as juyou } from "./juyou.content";
import { voice as juyouVoice } from "./juyou.voice";
import { content as tianxiong } from "./tianxiong.content";
import { voice as tianxiongVoice } from "./tianxiong.voice";
import { content as wangbuliuxing } from "./wangbuliuxing.content";
import { voice as wangbuliuxingVoice } from "./wangbuliuxing.voice";

// 「本草一问」系列的 Composition 注册表。竖屏 1080x1920，时长来自 voice 模块
// （= 各段旁白实际秒数之和 + 每段尾部呼吸），不写在组件里。
export const AskCompositions: React.FC = () => (
  <>
    <Composition
      id="AskDazaoYe"
      component={AskFilm}
      durationInFrames={dazaoYeVoice.totalFrames}
      fps={30}
      width={1080}
      height={1920}
      defaultProps={{ content: dazaoYe, voice: dazaoYeVoice }}
    />
    <Composition
      id="AskFangji"
      component={AskFilm}
      durationInFrames={fangjiVoice.totalFrames}
      fps={30}
      width={1080}
      height={1920}
      defaultProps={{ content: fangji, voice: fangjiVoice }}
    />
    <Composition
      id="AskJuyou"
      component={AskFilm}
      durationInFrames={juyouVoice.totalFrames}
      fps={30}
      width={1080}
      height={1920}
      defaultProps={{ content: juyou, voice: juyouVoice }}
    />
    <Composition
      id="AskTianxiong"
      component={AskFilm}
      durationInFrames={tianxiongVoice.totalFrames}
      fps={30}
      width={1080}
      height={1920}
      defaultProps={{ content: tianxiong, voice: tianxiongVoice }}
    />
    <Composition
      id="AskWangbuliuxing"
      component={AskFilm}
      durationInFrames={wangbuliuxingVoice.totalFrames}
      fps={30}
      width={1080}
      height={1920}
      defaultProps={{ content: wangbuliuxing, voice: wangbuliuxingVoice }}
    />
    {/* 系列总封面：单帧图，`npx remotion still AskSeriesCover out/asks/covers/…` 出它。
        它没有旁白也没有时长，注册成 Composition 只是为了让 Studio 和 CI 都看得见它。 */}
    <Composition
      id="AskSeriesCover"
      component={AskSeriesCover}
      durationInFrames={1}
      fps={30}
      width={1080}
      height={1920}
    />
  </>
);
