// AUTO-GENERATED by scripts/ask-build.ts from asks/dazao-ye.yaml — 不要手改。
// 改 YAML 之后重跑 `npm run ask:build`，CI 会检查这个文件是否与 YAML 同步。
import type { AskContent } from "./types";

export const content: AskContent = {
  "id": "dazao-ye",
  "entry": "大枣",
  "question": "古书里，大枣的叶子为什么单占一行？",
  "deck": "厨房里的本草 · 01",
  "collection": "厨房里的本草",
  "accent": "#a5613a",
  "segments": [
    {
      "role": "ask",
      "narration": "《神农本草经》写完大枣，又添了一句，写的是它的叶子。",
      "photos": [
        {
          "file": "jujuba-fruit-cluster.jpg",
          "caption": "大枣的果实",
          "credit": "古淑玲 / CC0"
        }
      ]
    },
    {
      "role": "object",
      "narration": "大枣是鼠李科的果子，秋天红透，晒干了就是厨房里那罐枣。它开很小的黄绿色花，叶子卵形，三出脉。",
      "photos": [
        {
          "file": "jujuba-flower-leaf.jpg",
          "caption": "叶与花",
          "credit": "ANDREW CONBOY / CC BY"
        },
        {
          "file": "jujuba-fruit-branch.jpg",
          "caption": "枝头的果",
          "credit": "古淑玲 / CC0"
        }
      ]
    },
    {
      "role": "book",
      "narration": "《神农本草经》把这一句写在大枣条的最后：叶覆麻黄，能令出汗。",
      "quote": {
        "text": "叶覆麻黄，能令出汗。",
        "source": "《神农本草经》卷一 · 上经"
      },
      "read": "叶覆麻黄，能令出汗。"
    },
    {
      "role": "study",
      "narration": "唐代《千金翼方》给叶子单立一篇，就叫「叶」；宋代《证类本草》照收；明代《本草纲目》注明它出自《本经》。明代卢之颐说，枣叶不自己发汗，是借麻黄之势。",
      "evidence": [
        {
          "text": "覆麻黄能令出汗，生河东平泽。",
          "source": "《千金翼方》· 唐",
          "note": "果部单立一篇，篇名就叫「叶」"
        },
        {
          "text": "覆麻黄，能令出汗。",
          "source": "《证类本草》· 宋",
          "note": "与《本经》同文照收"
        },
        {
          "text": "覆麻黄，能令出汗（《本经》）。",
          "source": "《本草纲目》· 明",
          "note": "李时珍注明它出自《本经》"
        },
        {
          "text": "覆麻黄，则扬液成汗，以能宣通津液，假麻黄张大之力耳。",
          "source": "《本草乘雅半偈》· 明",
          "note": "卢之颐：枣叶不自己发汗，借的是麻黄之力"
        }
      ]
    },
    {
      "role": "closing",
      "narration": "《本经》只给了它一行，这一行从唐代传到明代。下一味，橘柚。"
    }
  ],
  "sources": [
    "《神农本草经》卷一·上经（汉）",
    "《千金翼方》卷第四·本草下·果部（唐·孙思邈）",
    "《证类本草》（宋·唐慎微）",
    "《本草纲目》果部（明·李时珍）",
    "《本草乘雅半偈》（明·卢之颐）"
  ],
  "next": "橘柚——橘和柚，为什么算一味药？",
  "disclaimer": "古籍内容展示，不构成诊疗建议",
  "music": "music/fengguo-yanjiao.mp3"
};
