// AUTO-GENERATED by scripts/ask-build.ts from asks/fangji.yaml — 不要手改。
// 改 YAML 之后重跑 `npm run ask:build`，CI 会检查这个文件是否与 YAML 同步。
import type { AskContent } from "./types";

export const content: AskContent = {
  "id": "fangji",
  "entry": "防己",
  "question": "一味药为什么以「险健之人」为名？",
  "deck": "名字古怪的药 · 02",
  "collection": "名字古怪的药",
  "accent": "#4a6b5a",
  "segments": [
    {
      "role": "ask",
      "narration": "防己——一个药名，为什么读起来像在说一个人的品行？",
      "photos": [
        {
          "file": "sinomenium-acutum-leaf.jpg",
          "caption": "防己",
          "credit": "りなべる / CC BY"
        }
      ]
    },
    {
      "role": "object",
      "narration": "防己是藤本，茎像葛一样蔓延。根外面白、里面黄，切开有黑纹，像车辐。",
      "photos": [
        {
          "file": "sinomenium-acutum-vine.jpg",
          "caption": "茎像葛一样蔓延",
          "credit": "りなべる / CC BY"
        },
        {
          "file": "sinomenium-acutum-habit.jpg",
          "caption": "缠绕在别的树上",
          "credit": "WATANABE HITOSHI 渡辺仁 / CC BY"
        }
      ]
    },
    {
      "role": "book",
      "narration": "《本草纲目》引了李杲一句话：防己如险健之人，幸灾乐祸，能首为乱阶，若善用之，亦可御敌。",
      "quote": {
        "text": "防己如险健之人，幸灾乐祸，能首为乱阶，若善用之，亦可御敌。",
        "source": "《本草纲目》草部 · 防己 · 释名（引李杲语）"
      },
      "read": "防己如险健之人，幸灾乐祸，能首为乱阶，若善用之，亦可御敌。"
    },
    {
      "role": "study",
      "narration": "它的另一个名字叫「解离」，来自根上的黑纹。陶弘景写它：纹像车辐散开。",
      "evidence": [
        {
          "text": "解离，因其纹解也。",
          "source": "《本草纲目》· 释名",
          "note": "李时珍：《本经》的别名「解离」是照着根上的纹取的"
        },
        {
          "text": "其根外白内黄，如桔梗，内有黑纹如车辐解者，良。",
          "source": "《本草经集注》（《本草纲目》引）",
          "note": "陶弘景写它的样子，也是「解」这个字的来处"
        }
      ]
    },
    {
      "role": "closing",
      "narration": "一个药名可以是一句评价，也可以是一条纹路。下一味，天雄。"
    }
  ],
  "sources": [
    "《神农本草经》卷二·中经（汉）",
    "《本草经集注》（梁·陶弘景，见《本草纲目》引）",
    "李杲语（见《本草纲目》引）",
    "《本草纲目》草部（明·李时珍）"
  ],
  "next": "天雄——「沥节痛」是什么痛？",
  "disclaimer": "古籍内容展示，不构成诊疗建议",
  "music": "music/yuzhou-changwan.mp3"
};
