// AUTO-GENERATED by scripts/ask-build.ts from asks/juyou.yaml — 不要手改。
// 改 YAML 之后重跑 `npm run ask:build`，CI 会检查这个文件是否与 YAML 同步。
import type { AskContent } from "./types";

export const content: AskContent = {
  "id": "juyou",
  "entry": "橘柚",
  "question": "《神农本草经》为什么把橘和柚写成一味药？",
  "deck": "厨房里的本草 · 02",
  "collection": "厨房里的本草",
  "accent": "#a5613a",
  "segments": [
    {
      "role": "ask",
      "narration": "《神农本草经》把橘和柚写成了一条，可这一条最后的别名，写的是「橘皮」。",
      "photos": [
        {
          "file": "citrus-maxima-leaf.jpg",
          "caption": "柚",
          "credit": "KBKASH / CC0"
        }
      ]
    },
    {
      "role": "object",
      "narration": "柚是常绿的乔木。芸香科的叶子有个记号：叶柄上带一小片翼，叫箭叶。",
      "photos": [
        {
          "file": "citrus-maxima-leaf.jpg",
          "caption": "叶柄上那一小片翼，叫箭叶",
          "credit": "KBKASH / CC0"
        },
        {
          "file": "citrus-maxima-leaves.jpg",
          "caption": "柚叶",
          "credit": "KBKASH / CC0"
        }
      ]
    },
    {
      "role": "book",
      "narration": "《神农本草经》在这一条的末尾写了一个别名：一名橘皮。",
      "quote": {
        "text": "味辛，温。主胸中瘕热逆气，利水谷。久服，去臭、下气、通神。一名橘皮。生川谷。",
        "source": "《神农本草经》卷一 · 上经"
      },
      "read": "一名橘皮"
    },
    {
      "role": "study",
      "narration": "宋代寇宗奭说过：橘和柚本来就是两种，《本草》只写「一名橘皮」，是后人误加了柚字。到明代，李时珍干脆把柚单独立了一条。",
      "evidence": [
        {
          "text": "橘、柚自是两种。《本草》云∶一名橘皮。后人误加柚字，妄生分别。",
          "source": "《本草衍义》（《本草纲目》引）",
          "note": "宋人：这一对分别，是后人加出来的"
        },
        {
          "text": "柚，色油然，其状如卣，故名。",
          "source": "《本草纲目》果部 · 柚",
          "note": "李时珍给柚单独立目，并解释「柚」这个字"
        }
      ]
    },
    {
      "role": "closing",
      "narration": "从汉代到明代，一条药才分成两条。下一味，王不留行。"
    }
  ],
  "sources": [
    "《神农本草经》卷一·上经（汉）",
    "《本草衍义》（宋·寇宗奭，见《本草纲目》引）",
    "《本草纲目》果部（明·李时珍）"
  ],
  "next": "王不留行——一个药名，为什么像一句军令？",
  "disclaimer": "古籍内容展示，不构成诊疗建议",
  "music": "music/guzhen-lvxing.mp3"
};
