// AUTO-GENERATED by scripts/ask-build.ts from asks/tianxiong.yaml — 不要手改。
// 改 YAML 之后重跑 `npm run ask:build`，CI 会检查这个文件是否与 YAML 同步。
import type { AskContent } from "./types";

export const content: AskContent = {
  "id": "tianxiong",
  "entry": "天雄",
  "question": "「沥节痛」是什么痛？",
  "deck": "古书写错的字 · 01",
  "collection": "古书写错的字",
  "accent": "#4a6b5a",
  "segments": [
    {
      "role": "ask",
      "narration": "《神农本草经》里有一个病名，只有这一本书这么写。",
      "photos": [
        {
          "file": "aconitum-carmichaelii-flower.jpg",
          "caption": "天雄",
          "credit": "KADEN SLONE / CC BY"
        }
      ]
    },
    {
      "role": "object",
      "narration": "天雄是乌头的根。同一株植物，主根叫乌头，旁生的块根叫附子，长得独一份的叫天雄。",
      "photos": [
        {
          "file": "aconitum-carmichaelii-habit.jpg",
          "caption": "一片乌头",
          "credit": "SUSAN MARLEY / CC BY"
        },
        {
          "file": "aconitum-carmichaelii-plant.jpg",
          "caption": "独长的一株",
          "credit": "KADEN SLONE / CC BY"
        }
      ]
    },
    {
      "role": "book",
      "narration": "《神农本草经》给天雄记的病名里，有一个「沥节痛」。",
      "quote": {
        "text": "味辛，温。主大风，寒湿痹，沥节痛，拘挛缓急，破积聚邪气，金创，强筋骨，轻身健行。一名白幕。生山谷。",
        "source": "《神农本草经》卷二 · 中经"
      },
      "read": "沥节痛"
    },
    {
      "role": "study",
      "narration": "宋代的《证类本草》写「历节痛」，明代的《本草纲目》也写「历节痛」。「历节」是张仲景立的病名：关节疼痛遍历周身。",
      "evidence": [
        {
          "text": "主大风，寒湿痹，历节痛，拘挛缓急。",
          "source": "《证类本草》· 宋",
          "note": "「沥」作「历」"
        },
        {
          "text": "大风，寒湿痹，历节痛，拘挛缓急（《本经》）。",
          "source": "《本草纲目》· 明",
          "note": "李时珍也作「历」，并注明出自《本经》"
        },
        {
          "text": "中风历节病脉证并治第五",
          "source": "《金匮要略》· 汉",
          "note": "张仲景给「历节」立过专篇"
        }
      ]
    },
    {
      "role": "closing",
      "narration": "一个字写错，一个病名就消失了。下一味，藕实茎。"
    }
  ],
  "sources": [
    "《神农本草经》卷二·中经（汉）",
    "《金匮要略》（汉·张仲景）",
    "《证类本草》（宋·唐慎微）",
    "《本草纲目》草部（明·李时珍）"
  ],
  "next": "藕实茎——一条药名，为什么把三个部位连在一起？",
  "disclaimer": "古籍内容展示，不构成诊疗建议",
  "music": "music/gaoshan-liushui.mp3"
};
