// AUTO-GENERATED by scripts/generate-compositions.mjs - do not edit by hand.
// Run `npm run gen` after adding/removing files in src/finished/.
import { Composition } from "remotion";
import { createHerbalVideoProps } from "./herbal-data";
import {
  FormulaShortTemplate,
  HerbProfileTemplate,
  HerbalFeature,
} from "./HerbalVisuals";
import { GinsengFirstFilm } from "./finished/ginseng-first-film";
import { LicoriceSecondFilm } from "./finished/licorice-second-film";
import { PeonySecondFilm } from "./finished/peony-second-film";
import { BupleurumThirdFilm } from "./finished/bupleurum-third-film";
import { AngelicaFourthFilm } from "./finished/angelica-fourth-film";
import { AngelicaFourthFilmRealPhoto } from "./finished/angelica-fourth-film-real-photo";
import { HuangqiFirstFilm } from "./finished/huangqi-first-film";
import { EphedraFirstFilm } from "./finished/ephedra-first-film";
import { DanshaFirstFilm } from "./finished/dansha-first-film";
import { YunmuFirstFilm } from "./finished/yunmu-first-film";
import { YuquanFirstFilm } from "./finished/yuquan-first-film";
import { ShizhongruFirstFilm } from "./finished/shizhongru-first-film";
import { NieshiFirstFilm } from "./finished/nieshi-first-film";
import { XiaoshiFirstFilm } from "./finished/xiaoshi-first-film";
import { PuxiaoFirstFilm } from "./finished/puxiao-first-film";
import { HuashiFirstFilm } from "./finished/huashi-first-film";
import { KongqingFirstFilm } from "./finished/kongqing-first-film";
import { ZengqingFirstFilm } from "./finished/zengqing-first-film";
import { YuyuliangFirstFilm } from "./finished/yuyuliang-first-film";
import { TaiyiFirstFilm } from "./finished/taiyi-first-film";
import { BaishiyingFirstFilm } from "./finished/baishiying-first-film";
import { ZishiyingFirstFilm } from "./finished/zishiying-first-film";
import { BaiqingFirstFilm } from "./finished/baiqing-first-film";
import { BianqingFirstFilm } from "./finished/bianqing-first-film";
import { ChangpuFirstFilm } from "./finished/changpu-first-film";
import { JuhuaFirstFilm } from "./finished/juhua-first-film";
import { TianmendongFirstFilm } from "./finished/tianmendong-first-film";
import { GandihuangFirstFilm } from "./finished/gandihuang-first-film";
import { ShuFirstFilm } from "./finished/shu-first-film";
import { TusiziFirstFilm } from "./finished/tusizi-first-film";
import { NiuxiFirstFilm } from "./finished/niuxi-first-film";
import { ChongweiziFirstFilm } from "./finished/chongweizi-first-film";
import { NvweiFirstFilm } from "./finished/nvwei-first-film";
import { FangkuiFirstFilm } from "./finished/fangkui-first-film";
import { MaimendongFirstFilm } from "./finished/maimendong-first-film";
import { DuhuoFirstFilm } from "./finished/duhuo-first-film";
import { CheqianziFirstFilm } from "./finished/cheqianzi-first-film";
import { MuxiangFirstFilm } from "./finished/muxiang-first-film";
import { ShuyuFirstFilm } from "./finished/shuyu-first-film";
import { YiyirenFirstFilm } from "./finished/yiyiren-first-film";
import { ZexieFirstFilm } from "./finished/zexie-first-film";
import { YuanzhiFirstFilm } from "./finished/yuanzhi-first-film";
import { LongdanFirstFilm } from "./finished/longdan-first-film";
import { XixinFirstFilm } from "./finished/xixin-first-film";
import { ShihuFirstFilm } from "./finished/shihu-first-film";
import { BajitianFirstFilm } from "./finished/bajitian-first-film";
import { BaiyingFirstFilm } from "./finished/baiying-first-film";
import { BaihaoFirstFilm } from "./finished/baihao-first-film";
import { ChijianFirstFilm } from "./finished/chijian-first-film";
import { YanlvziFirstFilm } from "./finished/yanlvzi-first-film";
import { XiziFirstFilm } from "./finished/xizi-first-film";
import { ShishiFirstFilm } from "./finished/shishi-first-film";
import { ChizhiFirstFilm } from "./finished/chizhi-first-film";
import { QingzhiFirstFilm } from "./finished/qingzhi-first-film";
import { BaizhiFirstFilm } from "./finished/baizhi-first-film";
import { HuangzhiFirstFilm } from "./finished/huangzhi-first-film";
import { ZizhiFirstFilm } from "./finished/zizhi-first-film";
import { FangfengFirstFilm } from "./finished/fangfeng-first-film";
import { LanshiFirstFilm } from "./finished/lanshi-first-film";
import { JuemingziFirstFilm } from "./finished/juemingzi-first-film";
import { DazaoFirstFilm } from "./finished/dazao-first-film";
import { HumaFirstFilm } from "./finished/huma-first-film";
import { JuyouFirstFilm } from "./finished/juyou-first-film";
import { LongyanFirstFilm } from "./finished/longyan-first-film";
import { OushijingFirstFilm } from "./finished/oushijing-first-film";
import { PutaoFirstFilm } from "./finished/putao-first-film";
import { LuoshiFirstFilm } from "./finished/luoshi-first-film";
import { JiliziFirstFilm } from "./finished/jilizi-first-film";
import { RousongrongFirstFilm } from "./finished/rousongrong-first-film";

export const HerbalCompositions: React.FC = () => {
  return (
    <>
      <Composition
        id="HerbalFeature"
        component={HerbalFeature}
        durationInFrames={220}
        fps={30}
        width={1280}
        height={720}
        defaultProps={createHerbalVideoProps()}
      />
      <Composition
        id="HerbProfileTemplate"
        component={HerbProfileTemplate}
        durationInFrames={120}
        fps={30}
        width={1280}
        height={720}
        defaultProps={createHerbalVideoProps()}
      />
      <Composition
        id="FormulaShortTemplate"
        component={FormulaShortTemplate}
        durationInFrames={180}
        fps={30}
        width={1080}
        height={1920}
        defaultProps={createHerbalVideoProps()}
      />
      <Composition
        id="GinsengFirstFilm"
        component={GinsengFirstFilm}
        durationInFrames={240}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="LicoriceSecondFilm"
        component={LicoriceSecondFilm}
        durationInFrames={240}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="PeonySecondFilm"
        component={PeonySecondFilm}
        durationInFrames={240}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="BupleurumThirdFilm"
        component={BupleurumThirdFilm}
        durationInFrames={240}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="AngelicaFourthFilm"
        component={AngelicaFourthFilm}
        durationInFrames={240}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="AngelicaFourthFilmRealPhoto"
        component={AngelicaFourthFilmRealPhoto}
        durationInFrames={240}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="HuangqiFirstFilm"
        component={HuangqiFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="EphedraFirstFilm"
        component={EphedraFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="DanshaFirstFilm"
        component={DanshaFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="YunmuFirstFilm"
        component={YunmuFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="YuquanFirstFilm"
        component={YuquanFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="ShizhongruFirstFilm"
        component={ShizhongruFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="NieshiFirstFilm"
        component={NieshiFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="XiaoshiFirstFilm"
        component={XiaoshiFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="PuxiaoFirstFilm"
        component={PuxiaoFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="HuashiFirstFilm"
        component={HuashiFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="KongqingFirstFilm"
        component={KongqingFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="ZengqingFirstFilm"
        component={ZengqingFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="YuyuliangFirstFilm"
        component={YuyuliangFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="TaiyiFirstFilm"
        component={TaiyiFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="BaishiyingFirstFilm"
        component={BaishiyingFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="ZishiyingFirstFilm"
        component={ZishiyingFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="BaiqingFirstFilm"
        component={BaiqingFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="BianqingFirstFilm"
        component={BianqingFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="ChangpuFirstFilm"
        component={ChangpuFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="JuhuaFirstFilm"
        component={JuhuaFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="TianmendongFirstFilm"
        component={TianmendongFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="GandihuangFirstFilm"
        component={GandihuangFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="ShuFirstFilm"
        component={ShuFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="TusiziFirstFilm"
        component={TusiziFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="NiuxiFirstFilm"
        component={NiuxiFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="ChongweiziFirstFilm"
        component={ChongweiziFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="NvweiFirstFilm"
        component={NvweiFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="FangkuiFirstFilm"
        component={FangkuiFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="MaimendongFirstFilm"
        component={MaimendongFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="DuhuoFirstFilm"
        component={DuhuoFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="CheqianziFirstFilm"
        component={CheqianziFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="MuxiangFirstFilm"
        component={MuxiangFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="ShuyuFirstFilm"
        component={ShuyuFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="YiyirenFirstFilm"
        component={YiyirenFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="ZexieFirstFilm"
        component={ZexieFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="YuanzhiFirstFilm"
        component={YuanzhiFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="LongdanFirstFilm"
        component={LongdanFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="XixinFirstFilm"
        component={XixinFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="ShihuFirstFilm"
        component={ShihuFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="BajitianFirstFilm"
        component={BajitianFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="BaiyingFirstFilm"
        component={BaiyingFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="BaihaoFirstFilm"
        component={BaihaoFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="ChijianFirstFilm"
        component={ChijianFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="YanlvziFirstFilm"
        component={YanlvziFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="XiziFirstFilm"
        component={XiziFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="ShishiFirstFilm"
        component={ShishiFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="ChizhiFirstFilm"
        component={ChizhiFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="QingzhiFirstFilm"
        component={QingzhiFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="BaizhiFirstFilm"
        component={BaizhiFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="HuangzhiFirstFilm"
        component={HuangzhiFirstFilm}
        durationInFrames={630}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="ZizhiFirstFilm"
        component={ZizhiFirstFilm}
        durationInFrames={630}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="FangfengFirstFilm"
        component={FangfengFirstFilm}
        durationInFrames={630}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="LanshiFirstFilm"
        component={LanshiFirstFilm}
        durationInFrames={540}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="JuemingziFirstFilm"
        component={JuemingziFirstFilm}
        durationInFrames={630}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="DazaoFirstFilm"
        component={DazaoFirstFilm}
        durationInFrames={900}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="HumaFirstFilm"
        component={HumaFirstFilm}
        durationInFrames={720}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="JuyouFirstFilm"
        component={JuyouFirstFilm}
        durationInFrames={630}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="LongyanFirstFilm"
        component={LongyanFirstFilm}
        durationInFrames={720}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="OushijingFirstFilm"
        component={OushijingFirstFilm}
        durationInFrames={630}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="PutaoFirstFilm"
        component={PutaoFirstFilm}
        durationInFrames={720}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="LuoshiFirstFilm"
        component={LuoshiFirstFilm}
        durationInFrames={720}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="JiliziFirstFilm"
        component={JiliziFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
      <Composition
        id="RousongrongFirstFilm"
        component={RousongrongFirstFilm}
        durationInFrames={360}
        fps={30}
        width={1080}
        height={1920}
      />
    </>
  );
};
