// AUTO-GENERATED by scripts/sync-music.mjs - do not edit by hand.
// Run `npm run sync-music` after changing anything in ../../music.
//
// `frames` is the track's own length in the 30fps frames the compositions run at, counted
// from the file's frame headers rather than estimated from its size. FinishedMusic needs
// it: @remotion/media's `loop` takes the loop length from `trimAfter`, and a film-length
// `trimAfter` makes the loop silently degenerate into "play once". See the comment on
// `FinishedMusic` in src/finished-shell.tsx.
//
// `leadFrames` is how long the track spends silent before its first note. Looping from
// frame 0 puts that silence at every seam; skipping it is what keeps the bed continuous.

export type MusicTrack = {
  /** Basename under public/music. */
  file: string;
  title: string;
  /** Where the file came from. */
  source: string;
  /** "unrecorded" until someone writes down what the licence actually is. */
  license: string;
  seconds: number;
  /** The track's own length at 30fps. */
  frames: number;
  /** Silent frames at the head of the track; where a loop should start. */
  leadFrames: number;
  /** Silent seconds at the tail, kept as the track's natural ending. */
  tailSeconds: number;
};

export const MUSIC_REGISTRY: readonly MusicTrack[] = [
  {
    file: "gaoshan-liushui.mp3",
    title: "高山流水",
    source: "轻音乐网",
    license: "unrecorded",
    seconds: 210.442,
    frames: 6313,
    leadFrames: 0,
    tailSeconds: 0,
  },
  {
    file: "yuzhou-changwan.mp3",
    title: "渔舟唱晚（古筝）",
    source: "爱给网",
    license: "unrecorded",
    seconds: 255.948,
    frames: 7678,
    leadFrames: 29,
    tailSeconds: 0.553,
  },
  {
    file: "guzhen-lvxing.mp3",
    title: "古镇旅行（中国风）",
    source: "爱给网",
    license: "unrecorded",
    seconds: 163.265,
    frames: 4898,
    leadFrames: 2,
    tailSeconds: 0,
  },
  {
    file: "kongyin-gujian.mp3",
    title: "箜音古涧（箜篌）",
    source: "爱给网",
    license: "unrecorded",
    seconds: 99.192,
    frames: 2976,
    leadFrames: 0,
    tailSeconds: 0,
  },
  {
    file: "fengguo-yanjiao.mp3",
    title: "风过檐角轻",
    source: "爱给网",
    license: "unrecorded",
    seconds: 113.084,
    frames: 3393,
    leadFrames: 0,
    tailSeconds: 1.074,
  },
];
